---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url:
sections:
  - type: directory
    path: content/menyy
    label: Menüüd
    create: all
    match: "**/*"
    templates:
      - menus
  - type: directory
    path: content
    label: Lehed
    create: all
    match: "**/*"
    exclude: "!(menyy)/*"
    templates:
      - pages
upload_dir: static/uploads
public_path: "uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
